techcampman/techdesign_kyoto_c

- TachDesiginKyotoInaka.xcodeproj/project.pbxproj
- TachDesiginKyotoInaka/EditOrderPlayListViewController.swift
> 順番入れ替え画面のViewControllerを作成した

- TachDesiginKyotoInaka.xcodeproj/project.pbxproj
- TachDesiginKyotoInaka/SongCell.swift
- TachDesiginKyotoInaka/SongListViewController.swift
- TachDesiginKyotoInaka/ViewController/PlaylistCell.swift
- TachDesiginKyotoInaka/ViewController/PlaylistDetailSongCell.swift
- TachDesiginKyotoInaka/ViewController/PlaylistDetailViewController.swift
- TachDesiginKyotoInaka/ViewController/PlaylistListViewController.swift
> cellのセットを統一

- Podfile
- Podfile.lock
- README.md
dragで移動できるCollectionViewのライブラリを追加
> cocoaPodsでDraggableCollectionViewを追加

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ViewController/PreSelectViewController.swift
- TachDesiginKyotoInaka/ViewController/SelectEightSongViewController.swift
画面遷移を追加！！！
SelectSongControllerの内容を、SelectEightSongControllerに移動しました
> add NavigationControl

- TachDesiginKyotoInaka.xcodeproj/project.pbxproj
- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/CreatePlaylistViewController.swift
> 公開非公開の見た目実装

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/MyPlaylistCollectionViewCell.swift
> Home画面のプレイリストにキャッシュを追加

- TachDesiginKyotoInaka.xcodeproj/project.pbxproj
- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/PageControl.swift
- TachDesiginKyotoInaka/ViewController/PreSelectViewController.swift
> Favorite以外から追加できないバグを修正

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/PageControl.swift
- TachDesiginKyotoInaka/SongListViewController.swift
- TachDesiginKyotoInaka/ViewController/PlaylistCell.swift
- TachDesiginKyotoInaka/ViewController/PlaylistListViewController.swift
- TachDesiginKyotoInaka/ViewController/PreSelectViewController.swift
テーブルの位置を修正
PageControlで無限にsubviewが追加されるバグを削除
選択された曲一覧を更新
> テーブルの位置を修正

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
> Homeのヘッダのレイヤーを上に

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ViewController/EditOrderPlayListViewController.swift
- TachDesiginKyotoInaka/ViewController/SelectEightSongViewController.swift
> 詳細画面と曲選択画面のテーブルビューがずれる問題を修正

- TachDesiginKyotoInaka.xcodeproj/project.pbxproj
- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/HomeViewController.swift
- TachDesiginKyotoInaka/MyPlaylistCollectionViewCell.swift
ブラーが濃くなる問題を解決（インスタンスが無限に生成されていた）
マジックナンバーとして標準のセルのサイズを渡して、無理やり初期化
OptionalをOptionalらしく
> ホームでブラーがおかしいバグを修正

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ConstantShare.swift
- TachDesiginKyotoInaka/CreatePlaylistNavigationController.swift
- TachDesiginKyotoInaka/ViewController/EditOrderPlayListViewController.swift
> ConstantSharedに色を宣言 ナビゲーションバーの色を変更

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ViewController/EditOrderPlayListViewController.swift
> テーブルの幅、完了ボタンのvalidation

- TachDesiginKyotoInaka/CreatePlaylistViewController.swift
> unify corner-radius

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ConstantShare.swift
- TachDesiginKyotoInaka/EditOrderSongTableViewCell.xib
- TachDesiginKyotoInaka/ViewController/EditOrderPlayListViewController.swift
- TachDesiginKyotoInaka/ViewController/SelectEightSongViewController.swift
> Dev design edit order song page

- TachDesiginKyotoInaka/SearchViewController.swift
> 検索ボックスの色を変更。プリセットしか使えないので妥協

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
> mood選択画面のtableを上に広げる

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
homeのcollectionViewの下に隙間があるような気がしたので修正
Layerを変更してtableViewの上にボタンを
+のLayerをボタンより上に
> homeのcollectionViewの下に隙間があるような気がしたので修正、Layerを変更

- TachDesiginKyotoInaka/Base.lproj/Main.storyboard
- TachDesiginKyotoInaka/ViewController/PreSelectViewController.swift
> loadが終わるまでNextをdisable

- TachDesiginKyotoInaka/SearchViewController.swift
search画面でkeyboardが開いたまま閉じられるとダサかったのを修正
> search画面でkeyboardが開いたまま閉じられるとダサかったのを修正

- TachDesiginKyotoInaka/HomeViewController.swift
> プレイリスト作成後、Homeに戻ると自動的にtopへscrollされる
